#!/bin/bash
ls -la 
 drwxr-xr-x 2 root root 137 Mar  8 05:25 .
drwxr-xr-x 5 root root  71 Mar  8 05:07 ..
-rw-r--r-- 1 root root 104 Mar  8 05:15 0-current_working_directory
-rw-r--r-- 1 root root  64 Mar  8 04:44 1-listit
-rw-r--r-- 1 root root  16 Mar  8 05:19 2-bring_me_home
-rw-r--r-- 1 root root  18 Mar  8 05:22 3-listfiles
-rw-r--r-- 1 root root   0 Mar  8 05:25 listmorefiles
-rw-r--r-- 1 root root   1 Mar  8 04:21 README.md
